export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";
export const RESET_ALL_TUTORIALS = "RESET_ALL_TUTORIALS";


export const REPO_GITHUB = "REPO_GITHUB";
export const FOLLOWERS_GITHUB = "FOLLOWERS_GITHUB";
export const FOLLOWING_GITHUB = "FOLLOWING_GITHUB";